### ISSUE TITLE
Problem in launching on windows

### ISSUE THREAD

**Issue by boscorelly** [andrewleech/plugin.program.chrome.launcher#5]
Hi,

i have a problem with the plugin and netflixbmc. Chrome 42 installed.

Here is the trace :
04:23:44 T:1972  NOTICE: Thread LanguageInvoker start, auto delete: false
04:23:44 T:1972  NOTICE: -->Python Interpreter Initialized<--
04:23:44 T:1972  NOTICE: Traceback (most recent call last):
                                              File "C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\default.py", line 36, in <module>
                                                import resources.lib.pyOpenSSL
                                              File "C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\resources\lib\pyOpenSSL__init__.py", line 66, in <module>
                                                import OpenSSL
                                            ImportError: No module named OpenSSL
04:23:44 T:1972  NOTICE: ERROR importing OpenSSL handler
04:23:44 T:1972   ERROR: C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\resources\lib\ndg\httpsclient\subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
                                              warnings.warn(import_error_msg)
04:23:44 T:1972   ERROR: C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\resources\lib\ndg\httpsclient\ssl_peer_verification.py:24: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
                                              warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
04:23:44 T:1972   ERROR: C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.video.netflixbmc\resources\lib\ndg\httpsclient\subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
                                              warnings.warn(import_error_msg)
04:23:44 T:6048  NOTICE: Thread LanguageInvoker start, auto delete: false
04:23:44 T:6048  NOTICE: -->Python Interpreter Initialized<--
04:23:44 T:6048  NOTICE: Debug Disable
04:23:44 T:6048  NOTICE: Full Path:
04:23:44 T:6048  NOTICE:  C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.program.chrome.launcher\browser.sh --start-maximized --disable-translate --disable-new-tab-first-run --no-default-browser-check --no-first-run --kiosk C:\Users\bosco\AppData\Roaming\Kodi\userdata\addon_data\plugin.program.chrome.launcher\black.html
04:23:45 T:6048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 193] %1 n�est pas une application Win32 valide
                                            Traceback (most recent call last):
                                              File "C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.program.chrome.launcher\default.py", line 387, in <module>
                                                showSite(url, stopPlayback, kiosk, userAgent)
                                              File "C:\Users\bosco\AppData\Roaming\Kodi\addons\plugin.program.chrome.launcher\default.py", line 215, in showSite
                                                proc = subprocess.Popen(fullUrl, shell=False, creationflags=creationflags, close_fds = True)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\subprocess.py", line 710, in **init**
                                                errread, errwrite)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\subprocess.py", line 958, in _execute_child
                                                startupinfo)
                                            WindowsError: [Error 193] %1 n�est pas une application Win32 valide
                                            -->End of Python script error report<--

**Comment by andrewleech** [comment]
Do you have "Use Browser Shell Script" enabled in netflixbmc settings,
or "Use custom Chrome/script path" in Chrome Launcher settings?

Could you also let me know what version of windows you're running, and whether it's x86 of x64? Thanks.

**Comment by boscorelly** [comment]
Hi,

No, all is disabled. Ive also reset all settings. Same problem.

Windows 7 x64, all up to date.

De : Andrew Leech [mailto:notifications@github.com] 
Envoyé : mercredi 22 avril 2015 23:36
À : andrewleech/plugin.program.chrome.launcher
Cc : Camille Ollié
Objet : Re: [plugin.program.chrome.launcher] Problem in launching on windows
(#5)

Do you have "Use Browser Shell Script" enabled in netflixbmc settings,
or "Use custom Chrome/script path" in Chrome Launcher settings?

Could you also let me know what version of windows you're running, and
whether it's x86 of x64? Thanks.


Reply to this email directly or view it on GitHub
<https://github.com/andrewleech/plugin.program.chrome.launcher/issues/5#issu
ecomment-95345229> .
<https://github.com/notifications/beacon/ADsb-9i9MN1S2R5x-0IKBm_oxlcds00Fks5
oCAvSgaJpZM4EEzvk.gif> 

__________ Information provenant d'ESET NOD32 Antivirus, version de la base
des signatures de virus 11518 (20150422) __________

Le message a été vérifié par ESET NOD32 Antivirus.

http://www.eset.com
